export const API_ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/categories.json",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections.json",
  BRANDS: "/brands.json",
  PRODUCTS: "/products.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  PRODUCT: "/product.json",
  PRO:"http://127.0.0.1:8000/api/products",
  SINGLE_PRODUCT: "http://127.0.0.1:8000/api/products/1",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products_best_seller.json",
  NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
  FLASH_SALE_PRODUCTS: "/products_flash_sale.json",
  SHOPS: "/shops.json",
  SHOP: "/shop.json",
  SEARCH: "/search.json",
  ORDERS: "/orders.json",
  ORDER: "/order.json",
  BANNER: "http://localhost:8000/api/slider",
  NEXT_PUBLIC_REST_ENDPOINT: "http://localhost:8000",
  ACCOUNT_DETAILS:"http://127.0.0.1:8000/api/me",
};
